#' Results from Smartodds version of Activity 1
#'
#' Data collected from Smartodds employees carrying out Activity 1 from Playing With Statistics
#'
#' @format
#' A data frame with 48 rows and 50 columns
#' Each row corresponds to one participant
#' The columns show the sequence of Heads ("H") and Tails ("T") provided by each participant
#'
#' @source {in-house}
#' @examples
#' apply(activity1_data_sm, 1, function(x) sum(x=="H")) %>% unlist # count number of heads generated by each participant
#'
#'
"activity1_data_sm"
