#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom dipsaus actionButtonStyled
#' @importFrom dplyr group_by
#' @importFrom dplyr summarise
#' @importFrom DT datatable
#' @importFrom DT DTOutput
#' @importFrom DT renderDT
#' @importFrom grid grid.draw
#' @importFrom gridExtra grid.arrange
#' @importFrom magrittr %>%
#' @importFrom MASS mvrnorm
#' @importFrom reshape2 melt
#' @importFrom scales pretty_breaks
#' @importFrom shiny br
#' @importFrom shiny column
#' @importFrom shiny fluidRow
#' @importFrom shiny h3
#' @importFrom shiny hr
#' @importFrom shiny imageOutput
#' @importFrom shiny insertUI
#' @importFrom shiny invalidateLater
#' @importFrom shiny isolate
#' @importFrom shiny modalDialog
#' @importFrom shiny observe
#' @importFrom shiny observeEvent
#' @importFrom shiny plotOutput
#' @importFrom shiny reactiveVal
#' @importFrom shiny reactiveValues
#' @importFrom shiny renderImage
#' @importFrom shiny renderText
#' @importFrom shiny selectInput
#' @importFrom shiny shinyApp
#' @importFrom shiny showModal
#' @importFrom shiny tabPanel
#' @importFrom shiny tabsetPanel
#' @importFrom shiny tags
#' @importFrom shiny textOutput
#' @importFrom shiny updateTabsetPanel
#' @importFrom shiny validate
#' @importFrom shinydashboard dashboardBody
#' @importFrom shinydashboard dashboardHeader
#' @importFrom shinydashboard dashboardPage
#' @importFrom shinydashboard dashboardSidebar
#' @importFrom shinyjs useShinyjs
## usethis namespace: end
NULL
